# Generated by Django 4.1.7 on 2023-04-19 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_activities_durations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Detail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image', models.ImageField(upload_to='')),
                ('area_cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_detail_area_cities', to='api.area_cities')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_detail_destination', to='api.destination')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_detail_state', to='api.state')),
            ],
        ),
    ]
